version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "jonhealy1"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jonhealy1"
    commit-message:
      prefix: "ci(deps):"
      include: "scope"